// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqN5GqyRHOASSSgqlcoKSW3r7uRUhn658',
    appId: '1:324769489294:web:851b4dc7e666db0cd984df',
    messagingSenderId: '324769489294',
    projectId: 'news-app-b4691',
    authDomain: 'news-app-b4691.firebaseapp.com',
    storageBucket: 'news-app-b4691.appspot.com',
    measurementId: 'G-8L2FHKB1Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ISWezorlrQpKw3fD0JM1tdTb2CbdSoo',
    appId: '1:324769489294:android:1e2680333656406ad984df',
    messagingSenderId: '324769489294',
    projectId: 'news-app-b4691',
    storageBucket: 'news-app-b4691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCV6QDrkqfUIbYoC1FNGs6bzq8T9U97ak',
    appId: '1:324769489294:ios:9a2b2def6e2346c5d984df',
    messagingSenderId: '324769489294',
    projectId: 'news-app-b4691',
    storageBucket: 'news-app-b4691.appspot.com',
    iosBundleId: 'com.example.modul4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCV6QDrkqfUIbYoC1FNGs6bzq8T9U97ak',
    appId: '1:324769489294:ios:392ba9e62c70488ed984df',
    messagingSenderId: '324769489294',
    projectId: 'news-app-b4691',
    storageBucket: 'news-app-b4691.appspot.com',
    iosBundleId: 'com.example.modul4.RunnerTests',
  );
}
