name: modul6
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
